import Clerk from "@/components/providers/clerk-provider";
import "../(home)/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Clerk>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Clerk>
  );
}
