import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/app/components/providers/query-client-provider";

const maven = PT_Serif({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={maven.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
